version: "3.3"
services:
  n8n:
    build: .
    image: maestrow/n8n-devapi
    container_name: n8n-devapi
    depends_on:
      - mitm
    volumes:
      - "${HOME}/.n8n:/home/node/.n8n"
      - "${HOME}/${REPOS_DIR}:/home/node/${REPOS_DIR}"
    ports:
      - 5678:5678
    networks:
      - n8n-devapi-mitm
    restart: unless-stopped
    environment:
      - http_proxy=http://mitm:8080
      - https_proxy=https://mitm:8080
      - NODE_TLS_REJECT_UNAUTHORIZED=0  

  mitm:
    image: mitmproxy/mitmproxy
    container_name: mitmweb
    tty: true
    ports:
      - 8080:8080
      - 8081:8081
    command: mitmweb --web-host 0.0.0.0
    networks:
      - n8n-devapi-mitm

networks:
  n8n-devapi-mitm:
